name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/stale@v7.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
        stale-pr-message: 'This pull request is stale because it has been open 30 days with no activity.'
        stale-issue-label: 'stale-issue'
        exempt-issue-labels: 'enhancement,documentation,good-first-issue,question'
        stale-pr-label: 'stale-pr'
        exempt-pr-labels: 'work-in-progress'
        days-before-stale: 30
        days-before-close: -1
